[workspace]

members = [
    "day-01-calorie-counting/rust",
    "day-02-rock-paper-scissors/rust",
    "day-03-rucksack-reorganization/rust",
    "day-04-camp-cleanup/rust",
    "day-06-tuning-trouble/rust",
    "day-07-no-space-left/rust"
]
